# Generated by Django 5.1.3 on 2024-12-03 14:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=300)),
                ('y', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Delivery Address',
                'verbose_name_plural': 'Delivery Addresses',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Surname')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='uploads/products/', verbose_name='Photo')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Amount')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('address', models.CharField(blank=True, default='', max_length=50, verbose_name='Address')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone Number')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Order placed time')),
                ('status', models.BooleanField(default=False, verbose_name='Order status')),
                ('delivery', models.BooleanField(default=False, verbose_name='Delivery status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.customer', verbose_name='Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
